### ISSUE TITLE
admin panel gets disabled

### ISSUE THREAD

**Issue by zelmor** [tatewake/dokuwiki-plugin-backup#33] opened 2018-12-10 18:44 UTC
**plugin version:** 2018-11-21
**Dokuwiki version:** 2017-02-19e "Frusterick Manners"

**Issue:** 
After installing the plugin, the admin panel is disabled/does not display. See attached screenshot.

**Is reproducible:** 
Yes. Disabling the plugin brings back the admin panel, enabling or reinstalling disables it again.

**Workaround:**
None. Did not try upgrading Dokuwiki as it should be backed up beforehand. 

Please let me know if this is a known error in our version, and can be fixed with an upgrade.

![admin-panel](https://user-images.githubusercontent.com/4656427/49753504-ecfab900-fcb3-11e8-840f-6f24c055b285.png)

**Comment by tatewake** [comment] 2018-12-25 11:03
Hi @zelmor , thanks for your report. Recently the plugin's code was refactored by DokuWiki's author Andi… and I believe the plugin is going to require a more recent version than you're running to operate properly.

Can you upgrade your DokuWiki to the latest stable version (2018-04-22a as of right now) and see if that resolves the issue?

**Comment by zelmor** [comment] 2018-12-28 17:18
I'll get back to you in late January when I'm back to work.

**Comment by tatewake** [comment] 2019-02-12 09:49
Hi there, I'm going to close this issue since I'm unable to reproduce this myself.

I believe this has to do with an older version of DokuWiki being used that's not compatible. In this case I believe an upgrade to latest stable version should be sufficient.

If you are able to test on your setup and still find an issue, please re-open this ticket or create a new ticket if you're unable to do so.

Thanks!

**Closed by tatewake** 2019-02-12 09:49 UTC
Labels: need reporter feedback
